const shopListData = [
    {
        id :1,
        pic: "/assets/images/list1.png",
        title: "Accumsan tincidunt",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        id:2,
        pic: "/assets/images/list2.png",
        title: "In nulla",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        id:3,
        pic: "/assets/images/list3.png",
        title: "Vel sem",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        id:4,
        pic: "/assets/images/list4.png",
        title: "Porttitor cum",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        id:5,
        pic: "/assets/images/list5.png",
        title: "Nunc in",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        id:6,
        pic: "/assets/images/list6.png",
        title: "Vitae facilisis",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        id:7,
        pic: "/assets/images/list7.png",
        title: "Curabitur lectus",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },  
    
]

export default shopListData
